name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache

      - name: Publish package
        run: deno publish
